baseURL = "https://jeromiglopez.github.io/"
languageCode = "en-us"
disableKinds = ["taxonomy"]

[build]
    writeStats = true

[params]
    title = "Sada Theme"
    author = "Darshan Baral"
    description = "About Me:"
    copyright = "© 2024 No rights reserved."
    theme = "dark" # `dark` or `light`

    # Profile section
    [params.profile]
        name = "Jeromi G. López Santiago"
        title = "Ph.D. Candidate"
        photo = "images/sicote.jpeg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "fab fa-github"
        url = "https://github.com/jeromiglopez"
        title = "GitHub"
		
		[[params.social.list]]
        icon = "ai ai-google-scholar"
        url = "#"
        title = "Google Scholar"
		
		[[params.social.list]]
        icon = "ai ai-researchgate"
        url = "https://www.researchgate.net/profile/Jeromi-Lopez-Santiago"
        title = "ResearchGate"	

        [[params.social.list]]
        icon = "ai ai-orcid"
        url = "https://orcid.org/0000-0001-7026-0041"
        title = "ORCID"	

        [[params.social.list]]
        icon = "ai ai-cv"
        url = "files/cv.pdf"
        title = "Download CV"	

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "Ph.D. Mechanical Engineering (Bio and Microscale Engineering)"
        college = "University of Puerto Rico - Mayagüez Campus"
        dates = "2025"
        thesis_title = "Design and Characterization of a Rapidly Prototyped Pneumatic Microfluidic Device for the Study of Vinculin Expression at Focal Adhesions in Response to Continuous Mechanical Stimulation. "
        thesis_link = "#"

        [[params.education.list]]
        degree = "M.Eng. Mechanical Engineering"
        college = "University of Puerto Rico - Mayagüez Campus"
        dates = "2024"

        [[params.education.list]]
        degree = "B.Sc. Mechanical Engineering"
        college = "University of Puerto Rico - Mayagüez Campus"
        dates = "2016"

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Fluent"
				
        [[params.language.list]]
        language = "Español"
        level = "Native"

    # Interests section
    [params.hobbies]
        title = "Hobbies"

        [[params.hobbies.list]]
        interest = "Lifting Weights"
		
		[[params.hobbies.list]]
        interest = "Cats"

        [[params.hobbies.list]]
        interest = "Planted Aquariums"

        [[params.hobbies.list]]
        interest = "Baking"

    [params.aboutme]
        description = "I am a Mechanical Engineer specializing in additive manufacturing, microfluidic systems, and computational analysis of complex systems. My expertise includes materials characterization, microfabrication, cellular mechanotransduction, and multi-physics simulations, with proficiency in finite element analysis and advanced computational methods. I have a proven track record in translating research into practical engineering solutions through rigorous experimental design and cross-functional collaboration."

    # Experiences section
    [params.experiences]
        title = "Experience"

        [[params.jobs.list]]
        position = "Graduate Research Assistant"
        dates = "2016 - *Present*"
		link = "#"
        company = "Biomechanics and Biomaterials Laboratory (Department of Mechanical Engineering, UPR - Mayagüez Campus)"
        details = "I designed and fabricated a PDMS microfluidic device for live-cell imaging using 3D printing, employed multiphysics software for device characterization, and conducted complex cell-stretching experiments. Additionally, I provided technical support to other projects and collaborated on interdisciplinary research"

    	[[params.jobs.list]]
        position = "Mechanical Engineer"
        dates = "2023 - 2024"
		link = "#"
        company = "U.S. Army Corps of Engineers - Engineering Research and Development Center"
        details = "I led a thermomechanical FEA study using Abaqus to predict and minimize warping in 3D-printed parts by optimizing printing parameters. Additionally, I critically reviewed literature on thermomechanical modeling of additive manufactured parts and documented fiber-reinforced composite repairs of aging steel hydraulic structures."

    # Projects section
    [params.projects]
        title = "Projects"

        [[params.projects.list]]
        title = "Comprehensive Cat Census and Management Plan for the Mayagüez Pueblo Area: A Citizen Based Strategy for Humane Population Control"
        url = "#"
        description = "This project aims to conduct a comprehensive cat census in the Mayagüez Pueblo area to gather data on the stray and feral cat population, utilizing methods such as transect surveys, camera trapping, and community engagement. The goal is to develop humane and effective management strategies to improve public health, enhance community engagement, and ensure the well-being of both the feline population and local residents."
		
    # Skills section
    [params.skills]
        title = "Skills"

        [[params.skills.list]]
        skill = "Materials Testing and Analysis"
        details = "Tensile, Compression, Flexural, Hardness, Fatigue, and Thermomechanical Testing"
        skillrating = 80 # out of 100
                
        [[params.skills.list]]
        skill = "Microfabrication and Microfluidics"
        details = "Soft-lithography, Etching, Molding, Assembly, and Testing of Microfluidic Devices"
        skillrating = 60
		
        [[params.skills.list]]
        skill = "Additive Manufacturing"
        details = "Fused Deposition Modeling (FDM), Stereolithography (SLA), Digital Light Processing (DLP), Thermomechanical Analysis of AM Parts"
        skillrating = 65

    	[[params.skills.list]]
        skill = "Computer Aided Design and Engineering"
        details = "Abaqus, SolidWorks, AutoCAD and Fusion 360, ANSYS, FreeCAD, COMSOL Multiphysics, and Elmer FEM Solver"
        skillrating = 70

        [[params.skills.list]]
        skill = "Programming"
        details = "Python, R, Julia, and MATLAB"
        skillrating = 60
